# Generated by Django 5.1.6 on 2025-04-11 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15, verbose_name='Vehicle Number')),
                ('vehicle_name', models.CharField(max_length=50, verbose_name='Vehicle Model Name')),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Scooty', 'Scooty')], default='Bike', max_length=10, verbose_name='Vehicle Type')),
                ('driving_license', models.ImageField(upload_to='licenses/', verbose_name='Driving License')),
                ('govt_id', models.ImageField(upload_to='govt_id/', verbose_name='Government Id Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_boy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
