# Generated by Django 5.1.6 on 2025-04-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboymodel',
            name='salary',
            field=models.IntegerField(default=5000, verbose_name='Your salary'),
        ),
        migrations.AddField(
            model_name='deliveryboymodel',
            name='working_hours',
            field=models.IntegerField(default=10, verbose_name='Your Working Hours'),
        ),
    ]
