# Generated by Django 5.1.6 on 2025-04-03 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='designer/certificate/', verbose_name='Certificate')),
                ('experience', models.IntegerField(verbose_name='Experience in years')),
                ('skills', models.CharField(max_length=255, verbose_name='Skills')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='designer/portfolio/', verbose_name='Portfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignerBusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Name')),
                ('business_address', models.TextField(verbose_name='Address')),
                ('business_contact_no', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('business_description', models.TextField(verbose_name='Description')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_business_details', to='designer.designerregister')),
            ],
        ),
    ]
