# Generated by Django 5.1.6 on 2025-04-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_category', models.CharField(choices=[('men_ethnic', "Men's Ethnic Wear"), ('men_casual', "Men's Casual Wear"), ('men_formal', "Men's Formal Wear"), ('women_ethnic', "Women's Ethnic Wear"), ('women_casual', "Women's Casual Wear"), ('women_formal', "Women's Formal Wear")], max_length=50, verbose_name='Category')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='designer.designerregister')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productdetailsmodel')),
            ],
        ),
    ]
